[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["choguun <visaruth.s@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
openai = "^1.54.4"
tweepy = "^4.14.0"
pytest = "^8.3.3"
swarm = {git = "ssh://git@github.com/openai/swarm.git"}
setuptools = "^75.5.0"
web3 = "7.2.0"
cdp-sdk = "^0.10.3"
fastapi = "^0.115.5"
uvicorn = "^0.32.0"
motor = "^3.6.0"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ai_agent = 'ai_agent.main:main'
